// Which pages show which dashboard clip (public/clips/<name>.mp4, silent loops that play as they scroll into view).
export const CLIPS: Record<string, { name: string; alt: string; caption: string }> = {
  "/features/paywalls": { name: "revenuedot-loop-paywalls-v1", alt: "Picking the trial timeline paywall template in RevenueDot, creating it, and editing its layers in the visual editor", caption: "Template to editor in a few clicks. Recorded in the RevenueDot dashboard with demo data." },
  "/features/funnels": { name: "funnels", alt: "Stepping through a web-to-app funnel in the RevenueDot funnel builder: a question, a plan page, an email step, the paywall and the success page", caption: "The funnel builder with its live phone preview. Recorded with demo data." },
  "/solutions/web-to-app": { name: "funnels", alt: "Stepping through a web-to-app funnel in the RevenueDot funnel builder", caption: "A web funnel from question to paywall. Recorded with demo data." },
  "/features/experiments": { name: "revenuedot-loop-experiments-v1", alt: "Opening the 'Annual plan first on the paywall' experiment from the list and moving across its results table of control and treatment", caption: "An experiment and its results. Recorded in the RevenueDot dashboard with demo data." },
  "/features/customer-center": { name: "customer-center", alt: "Scrolling the Customer Center editor and opening its phone preview, then switching the preview between dark and light", caption: "The Customer Center editor with its phone preview. Recorded with demo data." },
  "/features/web-billing": { name: "web-checkout", alt: "On the hosted purchase page: switching between the Annual and Monthly plans, opening the discount code field, typing SPRING20 and applying it", caption: "The hosted purchase page RevenueDot serves, with a discount code applied. Recorded with example products." },
  "/features/purchase-links": { name: "web-checkout", alt: "On the hosted purchase page a purchase link opens: switching between the Annual and Monthly plans and applying the discount code SPRING20", caption: "What a purchase link opens: the hosted purchase page, with plans and a discount code. Recorded with example products." },
  "/features/charts": { name: "revenuedot-loop-charts-v1", alt: "Clicking through the MRR, Revenue, Active Subscriptions, Trial Conversion Funnel, Subscription Status and MRR Movement charts in RevenueDot", caption: "Six of the 43 charts. Recorded in the RevenueDot dashboard with demo data." },
  "/charts": { name: "revenuedot-loop-charts-v1", alt: "Clicking through the MRR, Revenue, Active Subscriptions, Trial Conversion Funnel, Subscription Status and MRR Movement charts in RevenueDot", caption: "Six of the 43 charts. Recorded in the RevenueDot dashboard with demo data." },
  "/features/integrations": { name: "revenuedot-loop-integrations-v1", alt: "Browsing the RevenueDot integrations catalogue and opening the Amplitude integration settings", caption: "The integrations catalogue. Recorded with demo data." },
  "/integrations": { name: "revenuedot-loop-integrations-v1", alt: "Browsing the RevenueDot integrations catalogue and opening the Amplitude integration settings", caption: "The integrations catalogue in the dashboard. Recorded with demo data." },
  "/features/customer-lists": { name: "revenuedot-loop-customers-v1", alt: "The Customers list with its filters, then one customer's page: the app user ID, the active entitlement and subscription, attributes and history", caption: "The customer list and a customer's page. Recorded with demo data." },
  "/features/refund-control": { name: "revenuedot-loop-lifecycle-v1", alt: "The Refund Control page with its refund rate and ordered policies, then the Payment recovery page with subscribers in billing retry and the recovery email settings", caption: "Refund Control, then Payment recovery. Recorded with demo data." },
  "/features/ai-connectors": { name: "revenuedot-loop-ai-v1", alt: "The RevenueDot AI page: the question 'How is revenue doing this month?' is typed and answered with the month's revenue, MRR, new and churned subscribers and a comparison with last month", caption: "RevenueDot AI answering a question about revenue. Recorded with demo data." },
};
