// The .md twin of a docs or blog page (RevenueCat and llms.txt convention: the same URL plus .md): the page's
// Markdown with frontmatter, links made absolute so it reads correctly out of context.
import { rewriteMarkdownLinks, SITE_URL } from "./docs-source.mjs";

export function markdownTwin(rel: string, data: { title: string; description: string }, body: string, path: string) {
  const yaml = (s: string) => JSON.stringify(s);
  const text = rewriteMarkdownLinks(rel, body.replace(/<!-- Generated by [^>]*-->\n*/g, ""), { md: true, absolute: true }).trim();
  return `---\ntitle: ${yaml(data.title)}\ndescription: ${yaml(data.description)}\nurl: ${SITE_URL}${path}\n---\n\n${text}\n`;
}

export const markdownResponse = (body: string) => new Response(body, { headers: { "Content-Type": "text/markdown; charset=utf-8" } });
