// Evidence pack: dated screenshots of every vendor page cited in compare.ts and alternatives.ts, captured 2026-10-04 with headless
// Chromium at 1280x800 (full pages at 1x, crops at 2x, light colour scheme, cookie banners declined or hidden). Generated by
// scripts/gen-evidence.mjs from scripts/evidence-pages.mjs after scripts/capture-evidence.mjs; do not edit by hand.
// Each crop proves one claim the comparison pages make; "alt" describes what is visible.
export type EvidenceCrop = {
  /** Short claim slug, e.g. "free-to-2500-then-1-percent". */
  claim: string;
  /** Asset path relative to this file, resolvable with import.meta.glob("../assets/evidence/**"). */
  file: string;
  /** What the crop shows, for the img alt text. */
  alt: string;
  /** "<Vendor> <page>, captured <date>: <the one claim it shows>." */
  caption: string;
};

export type Evidence = {
  vendor: string;
  /** Page slug, e.g. "pricing" or "docs-web-overview". */
  page: string;
  url: string;
  /** Capture date, ISO. */
  captured: string;
  /** Full-page screenshot (the first segment when the page was split; see fullParts). */
  full: string;
  /** All full-page segments in reading order, when the page was taller than 4,000 CSS px. */
  fullParts?: string[];
  crops: EvidenceCrop[];
};

const DATE = "2026-10-04";
const asset = (vendor: string, file: string) => `../assets/evidence/${vendor}/${file}`;

export const EVIDENCE: Evidence[] = [
  // ---- RevenueCat ----
  {
    vendor: "RevenueCat",
    page: "home",
    url: "https://www.revenuecat.com/",
    captured: DATE,
    full: asset("revenuecat", "home-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "home-full-1-2026-10-04.png"), asset("revenuecat", "home-full-2-2026-10-04.png"), asset("revenuecat", "home-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("revenuecat", "home-hero-2026-10-04.png"),
        alt: "RevenueCat homepage hero: the headline 'Build and grow your app business' with the Start for free button and the stats row.",
        caption: "RevenueCat homepage, captured 2026-10-04: Homepage hero.",
      },
      {
        claim: "apps-and-revenue",
        file: asset("revenuecat", "home-apps-and-revenue-2026-10-04.png"),
        alt: "RevenueCat homepage stats: apps supported, API requests daily and revenue processed.",
        caption: "RevenueCat homepage, captured 2026-10-04: The homepage cites 149K+ apps supported and $17B+ revenue processed.",
      },
      {
        claim: "paywall-templates",
        file: asset("revenuecat", "home-paywall-templates-2026-10-04.png"),
        alt: "RevenueCat homepage section on paywalls: pre-built configurable templates and a layer-driven editor.",
        caption: "RevenueCat homepage, captured 2026-10-04: Remotely configurable paywall editor with pre-built templates.",
      },
      {
        claim: "refund-handling",
        file: asset("revenuecat", "home-refund-handling-2026-10-04.png"),
        alt: "RevenueCat homepage section 'Automate refund handling' describing automatic management of Apple refund requests.",
        caption: "RevenueCat homepage, captured 2026-10-04: Automated Apple refund handling.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "pricing",
    url: "https://www.revenuecat.com/pricing/",
    captured: DATE,
    full: asset("revenuecat", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "pricing-full-1-2026-10-04.png"), asset("revenuecat", "pricing-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-to-2500-then-1-percent",
        file: asset("revenuecat", "pricing-free-to-2500-then-1-percent-2026-10-04.png"),
        alt: "RevenueCat pricing: the Pro card says 'Pay nothing for up to $2,500 in monthly tracked revenue. Then pay 1% of what you track once you hit $2,500 in MTR.'",
        caption: "RevenueCat pricing page, captured 2026-10-04: Free to $2,500 monthly tracked revenue, then 1% of what you track.",
      },
      {
        claim: "growth-tools-1-percent",
        file: asset("revenuecat", "pricing-growth-tools-1-percent-2026-10-04.png"),
        alt: "RevenueCat pricing: Growth Tools section with 'Only pay 1% of MTR on what you track'.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Growth Tools charge 1% only on what they track.",
      },
      {
        claim: "features",
        file: asset("revenuecat", "pricing-features-2026-10-04.png"),
        alt: "RevenueCat pricing 'All features included' grid: paywall editor with pre-built templates, A/B testing, segmentation, 40+ metrics, REST API, webhooks and support forums.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Paywall editor with templates, A/B testing, 40+ metrics and a REST API.",
      },
      {
        claim: "support",
        file: asset("revenuecat", "pricing-support-2026-10-04.png"),
        alt: "RevenueCat pricing feature list line 'Email and technical support forums'.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Email and technical support forums.",
      },
      {
        claim: "enterprise",
        file: asset("revenuecat", "pricing-enterprise-2026-10-04.png"),
        alt: "RevenueCat pricing Enterprise card: custom pricing, volume discounts, dedicated support and custom SLAs.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Enterprise adds dedicated support and custom SLAs.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "security-and-compliance",
    url: "https://www.revenuecat.com/security-and-compliance/",
    captured: DATE,
    full: asset("revenuecat", "security-and-compliance-full-2026-10-04.png"),
    crops: [
      {
        claim: "soc2",
        file: asset("revenuecat", "security-and-compliance-soc2-2026-10-04.png"),
        alt: "RevenueCat security page: SOC 2 Type II, audited annually, report available under NDA; GDPR and global privacy.",
        caption: "RevenueCat security and compliance page, captured 2026-10-04: SOC 2 Type II with the report under NDA, and GDPR.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "gdpr",
    url: "https://www.revenuecat.com/gdpr/",
    captured: DATE,
    full: asset("revenuecat", "gdpr-full-2026-10-04.png"),
    crops: [
      {
        claim: "processor",
        file: asset("revenuecat", "gdpr-processor-2026-10-04.png"),
        alt: "RevenueCat GDPR page: RevenueCat is a processor of end-user data; no hosting region is named.",
        caption: "RevenueCat GDPR page, captured 2026-10-04: GDPR processor; no hosting region named.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "community-pro-plan-payments",
    url: "https://community.revenuecat.com/general-questions-7/questions-about-pro-plan-payments-3618",
    captured: DATE,
    full: asset("revenuecat", "community-pro-plan-payments-full-2026-10-04.png"),
    crops: [
      {
        claim: "staff-reply-1-percent-of-whole-mtr",
        file: asset("revenuecat", "community-pro-plan-payments-staff-reply-1-percent-of-whole-mtr-2026-10-04.png"),
        alt: "RevenueCat community thread: staff reply 'We won't start charging you until you hit 2500 in MTR, but pricing will still be 1% of your whole MTR, so $25.'",
        caption: "RevenueCat community thread, captured 2026-10-04: Staff reply: 1% of the whole MTR once you reach $2,500.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "github-purchases-ios-license",
    url: "https://github.com/RevenueCat/purchases-ios/blob/main/LICENSE",
    captured: DATE,
    full: asset("revenuecat", "github-purchases-ios-license-full-2026-10-04.png"),
    crops: [
      {
        claim: "mit",
        file: asset("revenuecat", "github-purchases-ios-license-mit-2026-10-04.png"),
        alt: "GitHub file view of the purchases-ios LICENSE: MIT License text.",
        caption: "RevenueCat GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-quickstart",
    url: "https://www.revenuecat.com/docs/getting-started/quickstart",
    captured: DATE,
    full: asset("revenuecat", "docs-quickstart-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-quickstart-full-1-2026-10-04.png"), asset("revenuecat", "docs-quickstart-full-2-2026-10-04.png"), asset("revenuecat", "docs-quickstart-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "platforms",
        file: asset("revenuecat", "docs-quickstart-platforms-2026-10-04.png"),
        alt: "RevenueCat SDK quickstart: install step with the platform tabs Swift, Obj-C, Kotlin, Kotlin MP, Java, Flutter, React Native, Capacitor, Cordova and Unity.",
        caption: "RevenueCat docs page, captured 2026-10-04: SDKs for every mobile platform.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-web-overview",
    url: "https://www.revenuecat.com/docs/web/overview",
    captured: DATE,
    full: asset("revenuecat", "docs-web-overview-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-web-overview-full-1-2026-10-04.png"), asset("revenuecat", "docs-web-overview-full-2-2026-10-04.png"), asset("revenuecat", "docs-web-overview-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "stripe-paddle-billing",
        file: asset("revenuecat", "docs-web-overview-stripe-paddle-billing-2026-10-04.png"),
        alt: "RevenueCat Web docs overview: RevenueCat Billing (Stripe as gateway), Stripe Billing and Paddle Billing options.",
        caption: "RevenueCat docs page, captured 2026-10-04: Web Billing with Stripe and Paddle.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-web-stripe",
    url: "https://www.revenuecat.com/docs/web/integrations/stripe",
    captured: DATE,
    full: asset("revenuecat", "docs-web-stripe-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-web-stripe-full-1-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-2-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-3-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "unlock-entitlements",
        file: asset("revenuecat", "docs-web-stripe-unlock-entitlements-2026-10-04.png"),
        alt: "RevenueCat Stripe Billing docs: sell Stripe products through hosted Web Purchase Links, the Web SDK, and unlock entitlements on mobile.",
        caption: "RevenueCat docs page, captured 2026-10-04: Stripe Billing purchases unlock entitlements in the mobile app.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-third-party-integrations",
    url: "https://www.revenuecat.com/docs/integrations/third-party-integrations",
    captured: DATE,
    full: asset("revenuecat", "docs-third-party-integrations-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-third-party-integrations-full-1-2026-10-04.png"), asset("revenuecat", "docs-third-party-integrations-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "categories",
        file: asset("revenuecat", "docs-third-party-integrations-categories-2026-10-04.png"),
        alt: "RevenueCat third-party integrations docs: categories for customer engagement, data and product analytics, with the integration list.",
        caption: "RevenueCat docs page, captured 2026-10-04: Engagement and analytics integrations.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-scheduled-data-exports",
    url: "https://www.revenuecat.com/docs/integrations/scheduled-data-exports",
    captured: DATE,
    full: asset("revenuecat", "docs-scheduled-data-exports-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-scheduled-data-exports-full-1-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-2-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-3-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-4-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-5-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "destinations",
        file: asset("revenuecat", "docs-scheduled-data-exports-destinations-2026-10-04.png"),
        alt: "RevenueCat scheduled data exports docs: CSV or Parquet files delivered to Amazon S3, Google Cloud Storage, Azure Blob Storage or email.",
        caption: "RevenueCat docs page, captured 2026-10-04: Scheduled exports as CSV or Parquet to S3, GCS, Azure or email.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-customer-center",
    url: "https://www.revenuecat.com/docs/tools/customer-center",
    captured: DATE,
    full: asset("revenuecat", "docs-customer-center-full-2026-10-04.png"),
    crops: [
      {
        claim: "self-service-ui",
        file: asset("revenuecat", "docs-customer-center-self-service-ui-2026-10-04.png"),
        alt: "RevenueCat Customer Center docs: a self-service UI added to the app, available on Pro and Enterprise plans.",
        caption: "RevenueCat docs page, captured 2026-10-04: A no-code Customer Center.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-llms-txt",
    url: "https://www.revenuecat.com/docs/llms.txt",
    captured: DATE,
    full: asset("revenuecat", "docs-llms-txt-full-2026-10-04.png"),
    crops: [
      {
        claim: "virtual-currency",
        file: asset("revenuecat", "docs-llms-txt-virtual-currency-2026-10-04.png"),
        alt: "RevenueCat docs index (llms.txt): the Products & Offerings section covers offerings, product configuration and virtual currency.",
        caption: "RevenueCat docs page, captured 2026-10-04: Virtual currency and offerings in the docs.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-platform-resources-llms-txt",
    url: "https://www.revenuecat.com/docs/platform-resources/llms.txt",
    captured: DATE,
    full: asset("revenuecat", "docs-platform-resources-llms-txt-full-2026-10-04.png"),
    crops: [
      {
        claim: "amazon-galaxy",
        file: asset("revenuecat", "docs-platform-resources-llms-txt-amazon-galaxy-2026-10-04.png"),
        alt: "RevenueCat platform resources index: Amazon Platform Resources and Galaxy Store setup pages.",
        caption: "RevenueCat docs page, captured 2026-10-04: Amazon Appstore and Samsung Galaxy Store support.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-ai-toolkit",
    url: "https://www.revenuecat.com/docs/tools/ai-toolkit",
    captured: DATE,
    full: asset("revenuecat", "docs-ai-toolkit-full-2026-10-04.png"),
    crops: [
      {
        claim: "toolkit",
        file: asset("revenuecat", "docs-ai-toolkit-toolkit-2026-10-04.png"),
        alt: "RevenueCat AI toolkit docs: plugins, skills, an MCP server and a CLI for coding agents.",
        caption: "RevenueCat docs page, captured 2026-10-04: An AI toolkit with plugins, skills, an MCP server and a CLI.",
      },
    ],
  },
  // ---- Adapty ----
  {
    vendor: "Adapty",
    page: "home",
    url: "https://adapty.io/",
    captured: DATE,
    full: asset("adapty", "home-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "home-full-1-2026-10-04.png"), asset("adapty", "home-full-2-2026-10-04.png"), asset("adapty", "home-full-3-2026-10-04.png"), asset("adapty", "home-full-4-2026-10-04.png"), asset("adapty", "home-full-5-2026-10-04.png"), asset("adapty", "home-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("adapty", "home-hero-2026-10-04.png"),
        alt: "Adapty homepage hero: 'RevenueOS for subscription apps' with Book a demo and Start for free buttons.",
        caption: "Adapty homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "pricing",
    url: "https://adapty.io/pricing/",
    captured: DATE,
    full: asset("adapty", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "pricing-full-1-2026-10-04.png"), asset("adapty", "pricing-full-2-2026-10-04.png"), asset("adapty", "pricing-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "free-under-5k-then-1-percent",
        file: asset("adapty", "pricing-free-under-5k-then-1-percent-2026-10-04.png"),
        alt: "Adapty pricing plan cards: Pro is free while you earn under $5K/month, then 1% of monthly revenue after you pass $5K/month; Enterprise is custom pricing.",
        caption: "Adapty pricing page, captured 2026-10-04: Free under $5K a month, then 1% of monthly revenue.",
      },
      {
        claim: "add-ons",
        file: asset("adapty", "pricing-add-ons-2026-10-04.png"),
        alt: "Adapty pricing add-ons: Refund Saver 0.2%, Ads Manager 3.5% of ad spend, Mail 20%, payout acceleration 2.5% and attribution $0.03 per install, each free up to $5K.",
        caption: "Adapty pricing page, captured 2026-10-04: Add-on fees: Refund Saver 0.2%, Ads Manager 3.5%, Mail 20%, attribution $0.03.",
      },
      {
        claim: "templates-and-ab-tests",
        file: asset("adapty", "pricing-templates-and-ab-tests-2026-10-04.png"),
        alt: "Adapty pricing feature list: 50+ templates and AI generator, A/B tests with custom traffic splits, unlimited variants and early winner predictions.",
        caption: "Adapty pricing page, captured 2026-10-04: A/B tests with unlimited variants; 50+ templates.",
      },
      {
        claim: "soc2-and-residency",
        file: asset("adapty", "pricing-soc2-and-residency-2026-10-04.png"),
        alt: "Adapty pricing Enterprise section: 24/7 support in a dedicated Slack channel, data residency in the US or EU, SOC2 certified.",
        caption: "Adapty pricing page, captured 2026-10-04: US or EU data residency on Enterprise; SOC 2.",
      },
      {
        claim: "faq-what-counts",
        file: asset("adapty", "pricing-faq-what-counts-2026-10-04.png"),
        alt: "Adapty pricing FAQ, expanded: what counts toward monthly revenue.",
        caption: "Adapty pricing page, captured 2026-10-04: Revenue is counted before Apple, Google or Stripe take their share.",
      },
      {
        claim: "faq-migration",
        file: asset("adapty", "pricing-faq-migration-2026-10-04.png"),
        alt: "Adapty pricing FAQ, expanded: migrating from RevenueCat, Superwall or in-house typically takes a few days to a week.",
        caption: "Adapty pricing page, captured 2026-10-04: Adapty says a migration typically takes a few days to a week.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "security-and-compliance",
    url: "https://adapty.io/security-and-compliance/",
    captured: DATE,
    full: asset("adapty", "security-and-compliance-full-2026-10-04.png"),
    crops: [
      {
        claim: "soc2-type-ii",
        file: asset("adapty", "security-and-compliance-soc2-type-ii-2026-10-04.png"),
        alt: "Adapty security and compliance page: SOC 2 Type II attestation with the report available under NDA, and GDPR (EU and UK).",
        caption: "Adapty security and compliance page, captured 2026-10-04: SOC 2 Type II and GDPR.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "docs-migration-from-revenuecat",
    url: "https://adapty.io/docs/migration-from-revenuecat",
    captured: DATE,
    full: asset("adapty", "docs-migration-from-revenuecat-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "docs-migration-from-revenuecat-full-1-2026-10-04.png"), asset("adapty", "docs-migration-from-revenuecat-full-2-2026-10-04.png"), asset("adapty", "docs-migration-from-revenuecat-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "limits",
        file: asset("adapty", "docs-migration-from-revenuecat-limits-2026-10-04.png"),
        alt: "Adapty migration guide from RevenueCat: promotional or manually granted entitlements import as profiles without transactions; refund and billing-issue history is not carried over verbatim.",
        caption: "Adapty docs page, captured 2026-10-04: Promotional entitlements and refund history do not come across.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "github-adaptysdk-ios",
    url: "https://github.com/adaptyteam/AdaptySDK-iOS",
    captured: DATE,
    full: asset("adapty", "github-adaptysdk-ios-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "github-adaptysdk-ios-full-1-2026-10-04.png"), asset("adapty", "github-adaptysdk-ios-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "mit-license",
        file: asset("adapty", "github-adaptysdk-ios-mit-license-2026-10-04.png"),
        alt: "GitHub README of AdaptySDK-iOS: 'Adapty is available under the MIT license.'",
        caption: "Adapty GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "blog-new-pricing-2026",
    url: "https://adapty.io/blog/adapty-new-pricing-2026/",
    captured: DATE,
    full: asset("adapty", "blog-new-pricing-2026-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "blog-new-pricing-2026-full-1-2026-10-04.png"), asset("adapty", "blog-new-pricing-2026-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-to-5000",
        file: asset("adapty", "blog-new-pricing-2026-free-to-5000-2026-10-04.png"),
        alt: "Adapty blog post on its 2026 pricing: free until $5,000 in monthly tracked revenue, then 1% of revenue; Pro and Enterprise plans.",
        caption: "Adapty blog post, captured 2026-10-04: Free to $5,000 a month, then 1% of revenue.",
      },
    ],
  },
  // ---- Qonversion ----
  {
    vendor: "Qonversion",
    page: "home",
    url: "https://qonversion.io/",
    captured: DATE,
    full: asset("qonversion", "home-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "home-full-1-2026-10-04.png"), asset("qonversion", "home-full-2-2026-10-04.png"), asset("qonversion", "home-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("qonversion", "home-hero-2026-10-04.png"),
        alt: "Qonversion homepage hero: 'Ship subscriptions. Skip the drama.' with Start Free and Contact Sales.",
        caption: "Qonversion homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "pricing",
    url: "https://qonversion.io/pricing",
    captured: DATE,
    full: asset("qonversion", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "pricing-full-1-2026-10-04.png"), asset("qonversion", "pricing-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-to-7k-then-0-8-percent",
        file: asset("qonversion", "pricing-free-to-7k-then-0-8-percent-2026-10-04.png"),
        alt: "Qonversion pricing headline: 'Pro is 0.8% of tracked revenue — and you pay nothing until you pass $7K MTR.'",
        caption: "Qonversion pricing page, captured 2026-10-04: Free to $7K MTR, then 0.8% of tracked revenue.",
      },
      {
        claim: "faq-total-tracked-revenue",
        file: asset("qonversion", "pricing-faq-total-tracked-revenue-2026-10-04.png"),
        alt: "Qonversion pricing FAQ: 'Your bill becomes 0.8% of your total tracked revenue — not just the amount above $7K. At $8K MTR that's $64 a month; at $50K it's $400.'",
        caption: "Qonversion pricing page, captured 2026-10-04: 0.8% of all tracked revenue, not only the part above $7K.",
      },
      {
        claim: "plan-includes",
        file: asset("qonversion", "pricing-plan-includes-2026-10-04.png"),
        alt: "Qonversion pricing Pro plan list: all analytics with LTV and cohorts, Refund Keeper, unlimited apps and seats; Enterprise with an uptime SLA.",
        caption: "Qonversion pricing page, captured 2026-10-04: One Pro plan with every feature, unlimited apps and seats; Refund Keeper included.",
      },
      {
        claim: "compliance-and-support",
        file: asset("qonversion", "pricing-compliance-and-support-2026-10-04.png"),
        alt: "Qonversion pricing feature table: GDPR compliance, CCPA compliance, 24/7 priority support, unlimited seats, apps and projects.",
        caption: "Qonversion pricing page, captured 2026-10-04: GDPR and CCPA listed; 24/7 priority support; no SOC 2 listed.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "docs-stripe-integration",
    url: "https://documentation.qonversion.io/docs/stripe-integration",
    captured: DATE,
    full: asset("qonversion", "docs-stripe-integration-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "docs-stripe-integration-full-1-2026-10-04.png"), asset("qonversion", "docs-stripe-integration-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "stripe",
        file: asset("qonversion", "docs-stripe-integration-stripe-2026-10-04.png"),
        alt: "Qonversion Stripe integration docs: connect a Stripe account to manage cross-platform subscribers and track web payments.",
        caption: "Qonversion docs page, captured 2026-10-04: Stripe web payments.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "docs-mcp-server",
    url: "https://documentation.qonversion.io/docs/mcp-server",
    captured: DATE,
    full: asset("qonversion", "docs-mcp-server-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "docs-mcp-server-full-1-2026-10-04.png"), asset("qonversion", "docs-mcp-server-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "mcp-server",
        file: asset("qonversion", "docs-mcp-server-mcp-server-2026-10-04.png"),
        alt: "Qonversion MCP server docs: a remote MCP server at mcp.qonversion.io that lets AI assistants access project data, in beta.",
        caption: "Qonversion docs page, captured 2026-10-04: An MCP server for project data.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "docs-migrating-from-revenuecat",
    url: "https://documentation.qonversion.io/docs/migrating-from-revenuecat-to-qonversion",
    captured: DATE,
    full: asset("qonversion", "docs-migrating-from-revenuecat-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "docs-migrating-from-revenuecat-full-1-2026-10-04.png"), asset("qonversion", "docs-migrating-from-revenuecat-full-2-2026-10-04.png"), asset("qonversion", "docs-migrating-from-revenuecat-full-3-2026-10-04.png"), asset("qonversion", "docs-migrating-from-revenuecat-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "guide",
        file: asset("qonversion", "docs-migrating-from-revenuecat-guide-2026-10-04.png"),
        alt: "Qonversion docs: the written guide 'Migrating from RevenueCat'.",
        caption: "Qonversion docs page, captured 2026-10-04: A written guide for moving from RevenueCat.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "github-qonversion-ios-sdk",
    url: "https://github.com/qonversion/qonversion-ios-sdk",
    captured: DATE,
    full: asset("qonversion", "github-qonversion-ios-sdk-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "github-qonversion-ios-sdk-full-1-2026-10-04.png"), asset("qonversion", "github-qonversion-ios-sdk-full-2-2026-10-04.png"), asset("qonversion", "github-qonversion-ios-sdk-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "mit-license",
        file: asset("qonversion", "github-qonversion-ios-sdk-mit-license-2026-10-04.png"),
        alt: "GitHub README of qonversion-ios-sdk: 'Qonversion SDK is available under the MIT license.'",
        caption: "Qonversion GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  {
    vendor: "Qonversion",
    page: "revenuecat-alternative",
    url: "https://qonversion.io/revenuecat-alternative",
    captured: DATE,
    full: asset("qonversion", "revenuecat-alternative-full-1-2026-10-04.png"),
    fullParts: [asset("qonversion", "revenuecat-alternative-full-1-2026-10-04.png"), asset("qonversion", "revenuecat-alternative-full-2-2026-10-04.png"), asset("qonversion", "revenuecat-alternative-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "free-tier-comparison",
        file: asset("qonversion", "revenuecat-alternative-free-tier-comparison-2026-10-04.png"),
        alt: "Qonversion's RevenueCat comparison page: free tier up to $7K MTR, then 0.8% of tracked revenue versus RevenueCat's 1%.",
        caption: "Qonversion page /revenuecat-alternative, captured 2026-10-04: $7K free tier and 0.8% versus RevenueCat's $2.5K and 1%.",
      },
    ],
  },
  // ---- Superwall ----
  {
    vendor: "Superwall",
    page: "home",
    url: "https://superwall.com/",
    captured: DATE,
    full: asset("superwall", "home-full-1-2026-10-04.png"),
    fullParts: [asset("superwall", "home-full-1-2026-10-04.png"), asset("superwall", "home-full-2-2026-10-04.png"), asset("superwall", "home-full-3-2026-10-04.png"), asset("superwall", "home-full-4-2026-10-04.png"), asset("superwall", "home-full-5-2026-10-04.png"), asset("superwall", "home-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("superwall", "home-hero-2026-10-04.png"),
        alt: "Superwall homepage hero: 'AI powered monetization stack for mobile apps' with the annual revenue, paywall views and customer stats.",
        caption: "Superwall homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "pricing",
    url: "https://superwall.com/pricing",
    captured: DATE,
    full: asset("superwall", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("superwall", "pricing-full-1-2026-10-04.png"), asset("superwall", "pricing-full-2-2026-10-04.png"), asset("superwall", "pricing-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "infrastructure-free",
        file: asset("superwall", "pricing-infrastructure-free-2026-10-04.png"),
        alt: "Superwall pricing headline: subscription infrastructure (entitlements, purchase APIs, webhooks, SQL access) is free on every plan; only the paywall product is billed.",
        caption: "Superwall pricing page, captured 2026-10-04: Infrastructure free at any scale; only paywall revenue is billed.",
      },
      {
        claim: "indie-10k-then-1-percent",
        file: asset("superwall", "pricing-indie-10k-then-1-percent-2026-10-04.png"),
        alt: "Superwall pricing plan cards: Indie free up to $10k MAR then 1% of total MAR; Startup $49 a month + 1% of MAR; Scale $199 a month + 1% of MAR; Enterprise.",
        caption: "Superwall pricing page, captured 2026-10-04: Indie free to $10K MAR, then 1%; Startup $49 and Scale $199 a month.",
      },
      {
        claim: "attributed-revenue-only",
        file: asset("superwall", "pricing-attributed-revenue-only-2026-10-04.png"),
        alt: "Superwall pricing: 1% of revenue, paywall-attributed only; subscriptions purchased outside Superwall are free; no per-event or webhook fees.",
        caption: "Superwall pricing page, captured 2026-10-04: Billed only on paywall-attributed revenue.",
      },
      {
        claim: "sql-query-api",
        file: asset("superwall", "pricing-sql-query-api-2026-10-04.png"),
        alt: "Superwall pricing: the Query API gives SQL access to subscription data, included on every plan.",
        caption: "Superwall pricing page, captured 2026-10-04: Row-level SQL access on the Query API.",
      },
      {
        claim: "migration-agent",
        file: asset("superwall", "pricing-migration-agent-2026-10-04.png"),
        alt: "Superwall pricing: a coding agent performs the SDK swap, history port, entitlement port and webhook configuration in under an hour.",
        caption: "Superwall pricing page, captured 2026-10-04: An automated agent ports an app from RevenueCat in under an hour.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "docs-pricing-faq",
    url: "https://superwall.com/docs/support/faq/2801653905-how-does-superwalls-pricing-work",
    captured: DATE,
    full: asset("superwall", "docs-pricing-faq-full-2026-10-04.png"),
    crops: [
      {
        claim: "mar-definition",
        file: asset("superwall", "docs-pricing-faq-mar-definition-2026-10-04.png"),
        alt: "Superwall pricing FAQ: new MAR-based pricing with Indie $0, Startup $49, Scale $199; under $10k MAR is free; MAR is only revenue attributed to a Superwall paywall.",
        caption: "Superwall docs page, captured 2026-10-04: MAR is only revenue attributed to a Superwall paywall.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "blog-new-pricing",
    url: "https://superwall.com/blog/superwalls-new-pricing-more-aligned-generous-and-transparent",
    captured: DATE,
    full: asset("superwall", "blog-new-pricing-full-1-2026-10-04.png"),
    fullParts: [asset("superwall", "blog-new-pricing-full-1-2026-10-04.png"), asset("superwall", "blog-new-pricing-full-2-2026-10-04.png"), asset("superwall", "blog-new-pricing-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "date",
        file: asset("superwall", "blog-new-pricing-date-2026-10-04.png"),
        alt: "Superwall blog post header dated October 29, 2025 announcing the new pricing.",
        caption: "Superwall blog post, captured 2026-10-04: The pricing change was announced on October 29, 2025.",
      },
      {
        claim: "indie-free-to-10k",
        file: asset("superwall", "blog-new-pricing-indie-free-to-10k-2026-10-04.png"),
        alt: "Superwall blog: the Indie plan is 100% free up to $10K in Monthly Attributed Revenue; past $10K MAR the fee is 1% on total MAR.",
        caption: "Superwall blog post, captured 2026-10-04: Free to $10K MAR, then 1% of total MAR.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "llms-txt",
    url: "https://superwall.com/llms.txt",
    captured: DATE,
    full: asset("superwall", "llms-txt-full-1-2026-10-04.png"),
    fullParts: [asset("superwall", "llms-txt-full-1-2026-10-04.png"), asset("superwall", "llms-txt-full-2-2026-10-04.png"), asset("superwall", "llms-txt-full-3-2026-10-04.png"), asset("superwall", "llms-txt-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "coverage-and-limits",
        file: asset("superwall", "llms-txt-coverage-and-limits-2026-10-04.png"),
        alt: "Superwall llms.txt: coverage is the App Store, Google Play and Stripe; SDKs for iOS, Android, React Native, Flutter, Expo, Unity and Web; it does not run virtual currency, does not track ad revenue, and does not support Amazon or Roku.",
        caption: "Superwall docs page, captured 2026-10-04: No virtual currency, no ad revenue, no Amazon or Roku.",
      },
      {
        claim: "editor-mcp",
        file: asset("superwall", "llms-txt-editor-mcp-2026-10-04.png"),
        alt: "Superwall llms.txt: agent tooling with open-source skills, an editor MCP server and SQL access via the Query API.",
        caption: "Superwall docs page, captured 2026-10-04: An editor MCP server for coding agents.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "features-app-to-web-checkout",
    url: "https://superwall.com/features/app-to-web-checkout",
    captured: DATE,
    full: asset("superwall", "features-app-to-web-checkout-full-1-2026-10-04.png"),
    fullParts: [asset("superwall", "features-app-to-web-checkout-full-1-2026-10-04.png"), asset("superwall", "features-app-to-web-checkout-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "stripe-checkout",
        file: asset("superwall", "features-app-to-web-checkout-stripe-checkout-2026-10-04.png"),
        alt: "Superwall App-to-Web Checkout page: a paywall button opens a Stripe checkout in Safari and links the purchase back to the app.",
        caption: "Superwall page /features/app-to-web-checkout, captured 2026-10-04: App-to-Web Checkout with Stripe.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "legal-gdpr",
    url: "https://superwall.com/legal/gdpr",
    captured: DATE,
    full: asset("superwall", "legal-gdpr-full-2026-10-04.png"),
    crops: [
      {
        claim: "processor",
        file: asset("superwall", "legal-gdpr-processor-2026-10-04.png"),
        alt: "Superwall GDPR page: Superwall is a processor; it links a Data Processing Addendum; no SOC 2 report or hosting region is named.",
        caption: "Superwall page /legal/gdpr, captured 2026-10-04: GDPR processor with a DPA; no SOC 2 or hosting region named.",
      },
    ],
  },
  {
    vendor: "Superwall",
    page: "github-superwall-ios",
    url: "https://github.com/superwall/Superwall-iOS",
    captured: DATE,
    full: asset("superwall", "github-superwall-ios-full-2026-10-04.png"),
    crops: [
      {
        claim: "mit-license",
        file: asset("superwall", "github-superwall-ios-mit-license-2026-10-04.png"),
        alt: "GitHub repository page of Superwall-iOS with the MIT license shown in the About sidebar.",
        caption: "Superwall GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  // ---- Apphud ----
  {
    vendor: "Apphud",
    page: "home",
    url: "https://apphud.com/",
    captured: DATE,
    full: asset("apphud", "home-full-1-2026-10-04.png"),
    fullParts: [asset("apphud", "home-full-1-2026-10-04.png"), asset("apphud", "home-full-2-2026-10-04.png"), asset("apphud", "home-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("apphud", "home-hero-2026-10-04.png"),
        alt: "Apphud homepage hero: 'Skyrocket your app growth with a revenue data suite' for iOS and Android.",
        caption: "Apphud homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "pricing",
    url: "https://apphud.com/pricing",
    captured: DATE,
    full: asset("apphud", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("apphud", "pricing-full-1-2026-10-04.png"), asset("apphud", "pricing-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-10k-pro-expert",
        file: asset("apphud", "pricing-free-10k-pro-expert-2026-10-04.png"),
        alt: "Apphud pricing plan cards: Free with $10,000 MTR included and 1 seat; Pro with $5,000 MTR included and 5 seats; Expert with $5,000 MTR included and 10 seats.",
        caption: "Apphud pricing page, captured 2026-10-04: Free with $10K MTR; Pro and Expert include $5K.",
      },
      {
        claim: "overage-rates",
        file: asset("apphud", "pricing-overage-rates-2026-10-04.png"),
        alt: "Apphud pricing FAQ: $9.99 per additional $1,000 MTR on Pro, $11.99 on Expert; MTR is revenue in USD before Apple's cut and sandbox purchases are not counted.",
        caption: "Apphud pricing page, captured 2026-10-04: $9.99 per extra $1,000 on Pro, $11.99 on Expert.",
      },
      {
        claim: "grace-period",
        file: asset("apphud", "pricing-grace-period-2026-10-04.png"),
        alt: "Apphud pricing FAQ on a Free plan over $10,000: a 7-day grace period, then purchases are handled but renewals are not tracked and dashboard access ends.",
        caption: "Apphud pricing page, captured 2026-10-04: Over the free limit: 7-day grace period, then renewals stop being tracked.",
      },
      {
        claim: "seats-and-webhooks",
        file: asset("apphud", "pricing-seats-and-webhooks-2026-10-04.png"),
        alt: "Apphud pricing feature table: server-to-server webhooks, on-demand raw data exports and seats (1, 5, 10) per plan.",
        caption: "Apphud pricing page, captured 2026-10-04: Webhooks and exports on Expert and above; 1, 5 or 10 seats.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "data-protection",
    url: "https://apphud.com/data-protection",
    captured: DATE,
    full: asset("apphud", "data-protection-full-2026-10-04.png"),
    crops: [
      {
        claim: "eu-and-us",
        file: asset("apphud", "data-protection-eu-and-us-2026-10-04.png"),
        alt: "Apphud data protection page: data is stored in infrastructure located in the EU and US.",
        caption: "Apphud page /data-protection, captured 2026-10-04: Data stored in the EU and US.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "docs-web-payments",
    url: "https://docs.apphud.com/docs/web-payments",
    captured: DATE,
    full: asset("apphud", "docs-web-payments-full-2026-10-04.png"),
    crops: [
      {
        claim: "stripe-paddle",
        file: asset("apphud", "docs-web-payments-stripe-paddle-2026-10-04.png"),
        alt: "Apphud web payments docs: connect Stripe or Paddle to accept web payments in Apphud Flows.",
        caption: "Apphud docs page, captured 2026-10-04: Web payments through Stripe or Paddle.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "docs-llms-txt",
    url: "https://docs.apphud.com/llms.txt",
    captured: DATE,
    full: asset("apphud", "docs-llms-txt-full-1-2026-10-04.png"),
    fullParts: [asset("apphud", "docs-llms-txt-full-1-2026-10-04.png"), asset("apphud", "docs-llms-txt-full-2-2026-10-04.png"), asset("apphud", "docs-llms-txt-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "web-payments-and-s3",
        file: asset("apphud", "docs-llms-txt-web-payments-and-s3-2026-10-04.png"),
        alt: "Apphud docs index: Amazon S3 export and web payments through Stripe or Paddle for Flows.",
        caption: "Apphud docs page, captured 2026-10-04: Stripe and Paddle for Flows; Amazon S3 export.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "docs-mcp",
    url: "https://docs.apphud.com/docs/mcp",
    captured: DATE,
    full: asset("apphud", "docs-mcp-full-2026-10-04.png"),
    crops: [
      {
        claim: "public-mcp",
        file: asset("apphud", "docs-mcp-public-mcp-2026-10-04.png"),
        alt: "Apphud docs: a public MCP server lets AI assistants read analytics, inspect customers and manage paywalls.",
        caption: "Apphud docs page, captured 2026-10-04: A public MCP server.",
      },
    ],
  },
  {
    vendor: "Apphud",
    page: "github-apphudsdk",
    url: "https://github.com/apphud/ApphudSDK",
    captured: DATE,
    full: asset("apphud", "github-apphudsdk-full-1-2026-10-04.png"),
    fullParts: [asset("apphud", "github-apphudsdk-full-1-2026-10-04.png"), asset("apphud", "github-apphudsdk-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "mit-license",
        file: asset("apphud", "github-apphudsdk-mit-license-2026-10-04.png"),
        alt: "GitHub repository page of ApphudSDK with the MIT license shown in the About sidebar.",
        caption: "Apphud GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  // ---- Stripe ----
  {
    vendor: "Stripe",
    page: "pricing",
    url: "https://stripe.com/pricing",
    captured: DATE,
    full: asset("stripe", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("stripe", "pricing-full-1-2026-10-04.png"), asset("stripe", "pricing-full-2-2026-10-04.png"), asset("stripe", "pricing-full-3-2026-10-04.png"), asset("stripe", "pricing-full-4-2026-10-04.png"), asset("stripe", "pricing-full-5-2026-10-04.png"), asset("stripe", "pricing-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "card-fee",
        file: asset("stripe", "pricing-card-fee-2026-10-04.png"),
        alt: "Stripe pricing: 2.9% + 30¢ per successful card charge.",
        caption: "Stripe pricing page, captured 2026-10-04: 2.9% + 30¢ per successful US card charge.",
      },
      {
        claim: "international-cards",
        file: asset("stripe", "pricing-international-cards-2026-10-04.png"),
        alt: "Stripe pricing: an additional 1.5% for international cards.",
        caption: "Stripe pricing page, captured 2026-10-04: 1.5% more for international cards.",
      },
    ],
  },
  {
    vendor: "Stripe",
    page: "billing-pricing",
    url: "https://stripe.com/billing/pricing",
    captured: DATE,
    full: asset("stripe", "billing-pricing-full-1-2026-10-04.png"),
    fullParts: [asset("stripe", "billing-pricing-full-1-2026-10-04.png"), asset("stripe", "billing-pricing-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "0-7-percent",
        file: asset("stripe", "billing-pricing-0-7-percent-2026-10-04.png"),
        alt: "Stripe Billing pricing: 0.7% of Billing volume on the pay-as-you-go plan.",
        caption: "Stripe page /billing/pricing, captured 2026-10-04: Stripe Billing costs 0.7% of volume.",
      },
    ],
  },
  {
    vendor: "Stripe",
    page: "docs-checkout-quickstart",
    url: "https://docs.stripe.com/checkout/quickstart",
    captured: DATE,
    full: asset("stripe", "docs-checkout-quickstart-full-2026-10-04.png"),
    crops: [
      {
        claim: "hosted-page",
        file: asset("stripe", "docs-checkout-quickstart-hosted-page-2026-10-04.png"),
        alt: "Stripe Checkout quickstart: customers are redirected to a prebuilt payment page hosted by Stripe.",
        caption: "Stripe docs page, captured 2026-10-04: Checkout is a Stripe-hosted payment page.",
      },
    ],
  },
  {
    vendor: "Stripe",
    page: "docs-billing-analytics",
    url: "https://docs.stripe.com/billing/subscriptions/analytics",
    captured: DATE,
    full: asset("stripe", "docs-billing-analytics-full-2026-10-04.png"),
    crops: [
      {
        claim: "mrr-churn",
        file: asset("stripe", "docs-billing-analytics-mrr-churn-2026-10-04.png"),
        alt: "Stripe Billing analytics docs: MRR, churn and active subscriber metrics for Stripe subscriptions, with downloadable reports.",
        caption: "Stripe docs page, captured 2026-10-04: Billing analytics for Stripe subscriptions only.",
      },
    ],
  },
  // ---- Apple ----
  {
    vendor: "Apple",
    page: "app-review-guidelines",
    url: "https://developer.apple.com/app-store/review/guidelines/",
    captured: DATE,
    full: asset("apple", "app-review-guidelines-full-1-2026-10-04.png"),
    fullParts: [asset("apple", "app-review-guidelines-full-1-2026-10-04.png"), asset("apple", "app-review-guidelines-full-2-2026-10-04.png"), asset("apple", "app-review-guidelines-full-3-2026-10-04.png"), asset("apple", "app-review-guidelines-full-4-2026-10-04.png"), asset("apple", "app-review-guidelines-full-5-2026-10-04.png"), asset("apple", "app-review-guidelines-full-6-2026-10-04.png"), asset("apple", "app-review-guidelines-full-7-2026-10-04.png"), asset("apple", "app-review-guidelines-full-8-2026-10-04.png"), asset("apple", "app-review-guidelines-full-9-2026-10-04.png"), asset("apple", "app-review-guidelines-full-10-2026-10-04.png")],
    crops: [
      {
        claim: "3-1-1-in-app-purchase",
        file: asset("apple", "app-review-guidelines-3-1-1-in-app-purchase-2026-10-04.png"),
        alt: "Apple App Review Guidelines 3.1.1: apps that unlock features or functionality must use in-app purchase.",
        caption: "Apple page /app-store/review/guidelines/, captured 2026-10-04: Guideline 3.1.1 requires in-app purchase for digital unlocks.",
      },
    ],
  },
  {
    vendor: "Apple",
    page: "subscriptions",
    url: "https://developer.apple.com/app-store/subscriptions/",
    captured: DATE,
    full: asset("apple", "subscriptions-full-1-2026-10-04.png"),
    fullParts: [asset("apple", "subscriptions-full-1-2026-10-04.png"), asset("apple", "subscriptions-full-2-2026-10-04.png"), asset("apple", "subscriptions-full-3-2026-10-04.png"), asset("apple", "subscriptions-full-4-2026-10-04.png"), asset("apple", "subscriptions-full-5-2026-10-04.png"), asset("apple", "subscriptions-full-6-2026-10-04.png"), asset("apple", "subscriptions-full-7-2026-10-04.png")],
    crops: [
      {
        claim: "85-percent-after-one-year",
        file: asset("apple", "subscriptions-85-percent-after-one-year-2026-10-04.png"),
        alt: "Apple auto-renewable subscriptions page: 70% in the first year, then 85% after one year of paid service.",
        caption: "Apple page /app-store/subscriptions/, captured 2026-10-04: 70% in year one, 85% after one year.",
      },
      {
        claim: "small-business-program",
        file: asset("apple", "subscriptions-small-business-program-2026-10-04.png"),
        alt: "Apple subscriptions page: Small Business Program members receive 85% of the subscription price at each billing cycle.",
        caption: "Apple page /app-store/subscriptions/, captured 2026-10-04: 85% (a 15% fee) under the Small Business Program.",
      },
    ],
  },
  {
    vendor: "Apple",
    page: "storekit-in-app-purchase",
    url: "https://developer.apple.com/documentation/storekit/in-app_purchase",
    captured: DATE,
    full: asset("apple", "storekit-in-app-purchase-full-1-2026-10-04.png"),
    fullParts: [asset("apple", "storekit-in-app-purchase-full-1-2026-10-04.png"), asset("apple", "storekit-in-app-purchase-full-2-2026-10-04.png"), asset("apple", "storekit-in-app-purchase-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "overview",
        file: asset("apple", "storekit-in-app-purchase-overview-2026-10-04.png"),
        alt: "Apple StoreKit In-App Purchase documentation overview.",
        caption: "Apple page /documentation/storekit/in-app_purchase, captured 2026-10-04: StoreKit in-app purchase docs.",
      },
    ],
  },
  {
    vendor: "Apple",
    page: "app-store-server-notifications",
    url: "https://developer.apple.com/documentation/appstoreservernotifications",
    captured: DATE,
    full: asset("apple", "app-store-server-notifications-full-1-2026-10-04.png"),
    fullParts: [asset("apple", "app-store-server-notifications-full-1-2026-10-04.png"), asset("apple", "app-store-server-notifications-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "overview",
        file: asset("apple", "app-store-server-notifications-overview-2026-10-04.png"),
        alt: "Apple App Store Server Notifications documentation: a server-to-server service sending real-time notifications for in-app purchase events.",
        caption: "Apple page /documentation/appstoreservernotifications, captured 2026-10-04: App Store Server Notifications.",
      },
    ],
  },
  {
    vendor: "Apple",
    page: "github-app-store-server-library-node",
    url: "https://github.com/apple/app-store-server-library-node",
    captured: DATE,
    full: asset("apple", "github-app-store-server-library-node-full-1-2026-10-04.png"),
    fullParts: [asset("apple", "github-app-store-server-library-node-full-1-2026-10-04.png"), asset("apple", "github-app-store-server-library-node-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "readme",
        file: asset("apple", "github-app-store-server-library-node-readme-2026-10-04.png"),
        alt: "GitHub README of Apple's app-store-server-library-node.",
        caption: "Apple GitHub page, captured 2026-10-04: Apple's App Store Server Library for Node.js.",
      },
    ],
  },
  // ---- Google ----
  {
    vendor: "Google",
    page: "play-service-fees",
    url: "https://support.google.com/googleplay/android-developer/answer/112622?hl=en",
    captured: DATE,
    full: asset("google", "play-service-fees-full-2026-10-04.png"),
    crops: [
      {
        claim: "service-fees",
        file: asset("google", "play-service-fees-service-fees-2026-10-04.png"),
        alt: "Google Play service fees help page: 15% for the first $1M of revenue a year, 30% above that, and 15% for automatically renewing subscriptions regardless of revenue.",
        caption: "Google page /googleplay/android-developer/answer/112622, captured 2026-10-04: Google Play charges 15% on subscriptions.",
      },
    ],
  },
  {
    vendor: "Google",
    page: "play-payments-policy",
    url: "https://support.google.com/googleplay/android-developer/answer/9858738",
    captured: DATE,
    full: asset("google", "play-payments-policy-full-2026-10-04.png"),
    crops: [
      {
        claim: "billing-system",
        file: asset("google", "play-payments-policy-billing-system-2026-10-04.png"),
        alt: "Google Play Payments policy: apps charging for in-app features, digital content or goods must use Google Play's billing system.",
        caption: "Google page /googleplay/android-developer/answer/9858738, captured 2026-10-04: Digital purchases must use Google Play's billing system.",
      },
    ],
  },
  {
    vendor: "Google",
    page: "play-billing-integrate",
    url: "https://developer.android.com/google/play/billing/integrate",
    captured: DATE,
    full: asset("google", "play-billing-integrate-full-1-2026-10-04.png"),
    fullParts: [asset("google", "play-billing-integrate-full-1-2026-10-04.png"), asset("google", "play-billing-integrate-full-2-2026-10-04.png"), asset("google", "play-billing-integrate-full-3-2026-10-04.png"), asset("google", "play-billing-integrate-full-4-2026-10-04.png"), asset("google", "play-billing-integrate-full-5-2026-10-04.png"), asset("google", "play-billing-integrate-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "guide",
        file: asset("google", "play-billing-integrate-guide-2026-10-04.png"),
        alt: "Google Play Billing Library integration guide: how to integrate the library to start selling products.",
        caption: "Google page /google/play/billing/integrate, captured 2026-10-04: Play Billing Library integration guide.",
      },
    ],
  },
  // ---- Purchasely ----
  {
    vendor: "Purchasely",
    page: "home",
    url: "https://www.purchasely.com/",
    captured: DATE,
    full: asset("purchasely", "home-full-1-2026-10-04.png"),
    fullParts: [asset("purchasely", "home-full-1-2026-10-04.png"), asset("purchasely", "home-full-2-2026-10-04.png"), asset("purchasely", "home-full-3-2026-10-04.png"), asset("purchasely", "home-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("purchasely", "home-hero-2026-10-04.png"),
        alt: "Purchasely homepage hero: 'Turn app users into subscribers' with a Talk to sales button.",
        caption: "Purchasely homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Purchasely",
    page: "pricing",
    url: "https://www.purchasely.com/pricing",
    captured: DATE,
    full: asset("purchasely", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("purchasely", "pricing-full-1-2026-10-04.png"), asset("purchasely", "pricing-full-2-2026-10-04.png"), asset("purchasely", "pricing-full-3-2026-10-04.png"), asset("purchasely", "pricing-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "no-public-price",
        file: asset("purchasely", "pricing-no-public-price-2026-10-04.png"),
        alt: "Purchasely /pricing serves the homepage: 'Turn app users into subscribers' with a Talk to sales button and no prices.",
        caption: "Purchasely pricing page, captured 2026-10-04: No public pricing; the page directs to sales.",
      },
    ],
  },
  {
    vendor: "Purchasely",
    page: "docs",
    url: "https://docs.purchasely.com/",
    captured: DATE,
    full: asset("purchasely", "docs-full-2026-10-04.png"),
    crops: [
      {
        claim: "docs-home",
        file: asset("purchasely", "docs-docs-home-2026-10-04.png"),
        alt: "Purchasely documentation home page.",
        caption: "Purchasely docs page, captured 2026-10-04: Purchasely docs.",
      },
    ],
  },
  {
    vendor: "Purchasely",
    page: "github-purchasely-ios",
    url: "https://github.com/Purchasely/Purchasely-iOS",
    captured: DATE,
    full: asset("purchasely", "github-purchasely-ios-full-2026-10-04.png"),
    crops: [
      {
        claim: "about",
        file: asset("purchasely", "github-purchasely-ios-about-2026-10-04.png"),
        alt: "GitHub repository page of Purchasely-iOS; the About sidebar shows no recognized license.",
        caption: "Purchasely GitHub page, captured 2026-10-04: No recognized license on GitHub.",
      },
    ],
  },
];

/** Evidence for one vendor page, e.g. evidenceFor("RevenueCat", "pricing"). */
export const evidenceFor = (vendor: string, page: string): Evidence | undefined => EVIDENCE.find((e) => e.vendor === vendor && e.page === page);
