// Evidence pack: dated screenshots of every vendor page cited in compare.ts and alternatives.ts, captured 2026-10-04 with headless
// Chromium at 1280x800 (full pages at 1x, crops at 2x, light colour scheme, cookie banners declined or hidden). Generated by
// scripts/gen-evidence.mjs from scripts/evidence-pages.mjs after scripts/capture-evidence.mjs; do not edit by hand.
// Each crop proves one claim the comparison pages make; "alt" describes what is visible.
export type EvidenceCrop = {
  /** Short claim slug, e.g. "free-to-2500-then-1-percent". */
  claim: string;
  /** Asset path relative to this file, resolvable with import.meta.glob("../assets/evidence/**"). */
  file: string;
  /** What the crop shows, for the img alt text. */
  alt: string;
  /** "<Vendor> <page>, captured <date>: <the one claim it shows>." */
  caption: string;
};

export type Evidence = {
  vendor: string;
  /** Page slug, e.g. "pricing" or "docs-web-overview". */
  page: string;
  url: string;
  /** Capture date, ISO. */
  captured: string;
  /** Full-page screenshot (the first segment when the page was split; see fullParts). */
  full: string;
  /** All full-page segments in reading order, when the page was taller than 4,000 CSS px. */
  fullParts?: string[];
  crops: EvidenceCrop[];
};

const DATE = "2026-10-04";
const asset = (vendor: string, file: string) => `../assets/evidence/${vendor}/${file}`;

export const EVIDENCE: Evidence[] = [
  // ---- RevenueCat ----
  {
    vendor: "RevenueCat",
    page: "home",
    url: "https://www.revenuecat.com/",
    captured: DATE,
    full: asset("revenuecat", "home-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "home-full-1-2026-10-04.png"), asset("revenuecat", "home-full-2-2026-10-04.png"), asset("revenuecat", "home-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("revenuecat", "home-hero-2026-10-04.png"),
        alt: "RevenueCat homepage hero: the headline 'Build and grow your app business' with the Start for free button and the stats row.",
        caption: "RevenueCat homepage, captured 2026-10-04: Homepage hero.",
      },
      {
        claim: "apps-and-revenue",
        file: asset("revenuecat", "home-apps-and-revenue-2026-10-04.png"),
        alt: "RevenueCat homepage stats: apps supported, API requests daily and revenue processed.",
        caption: "RevenueCat homepage, captured 2026-10-04: The homepage cites 149K+ apps supported and $17B+ revenue processed.",
      },
      {
        claim: "paywall-templates",
        file: asset("revenuecat", "home-paywall-templates-2026-10-04.png"),
        alt: "RevenueCat homepage section on paywalls: pre-built configurable templates and a layer-driven editor.",
        caption: "RevenueCat homepage, captured 2026-10-04: Remotely configurable paywall editor with pre-built templates.",
      },
      {
        claim: "refund-handling",
        file: asset("revenuecat", "home-refund-handling-2026-10-04.png"),
        alt: "RevenueCat homepage section 'Automate refund handling' describing automatic management of Apple refund requests.",
        caption: "RevenueCat homepage, captured 2026-10-04: Automated Apple refund handling.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "pricing",
    url: "https://www.revenuecat.com/pricing/",
    captured: DATE,
    full: asset("revenuecat", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "pricing-full-1-2026-10-04.png"), asset("revenuecat", "pricing-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-to-2500-then-1-percent",
        file: asset("revenuecat", "pricing-free-to-2500-then-1-percent-2026-10-04.png"),
        alt: "RevenueCat pricing: the Pro card says 'Pay nothing for up to $2,500 in monthly tracked revenue. Then pay 1% of what you track once you hit $2,500 in MTR.'",
        caption: "RevenueCat pricing page, captured 2026-10-04: Free to $2,500 monthly tracked revenue, then 1% of what you track.",
      },
      {
        claim: "growth-tools-1-percent",
        file: asset("revenuecat", "pricing-growth-tools-1-percent-2026-10-04.png"),
        alt: "RevenueCat pricing: Growth Tools section with 'Only pay 1% of MTR on what you track'.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Growth Tools charge 1% only on what they track.",
      },
      {
        claim: "features",
        file: asset("revenuecat", "pricing-features-2026-10-04.png"),
        alt: "RevenueCat pricing 'All features included' grid: paywall editor with pre-built templates, A/B testing, segmentation, 40+ metrics, REST API, webhooks and support forums.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Paywall editor with templates, A/B testing, 40+ metrics and a REST API.",
      },
      {
        claim: "support",
        file: asset("revenuecat", "pricing-support-2026-10-04.png"),
        alt: "RevenueCat pricing feature list line 'Email and technical support forums'.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Email and technical support forums.",
      },
      {
        claim: "enterprise",
        file: asset("revenuecat", "pricing-enterprise-2026-10-04.png"),
        alt: "RevenueCat pricing Enterprise card: custom pricing, volume discounts, dedicated support and custom SLAs.",
        caption: "RevenueCat pricing page, captured 2026-10-04: Enterprise adds dedicated support and custom SLAs.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "security-and-compliance",
    url: "https://www.revenuecat.com/security-and-compliance/",
    captured: DATE,
    full: asset("revenuecat", "security-and-compliance-full-2026-10-04.png"),
    crops: [
      {
        claim: "soc2",
        file: asset("revenuecat", "security-and-compliance-soc2-2026-10-04.png"),
        alt: "RevenueCat security page: SOC 2 Type II, audited annually, report available under NDA; GDPR and global privacy.",
        caption: "RevenueCat security and compliance page, captured 2026-10-04: SOC 2 Type II with the report under NDA, and GDPR.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "gdpr",
    url: "https://www.revenuecat.com/gdpr/",
    captured: DATE,
    full: asset("revenuecat", "gdpr-full-2026-10-04.png"),
    crops: [
      {
        claim: "processor",
        file: asset("revenuecat", "gdpr-processor-2026-10-04.png"),
        alt: "RevenueCat GDPR page: RevenueCat is a processor of end-user data; no hosting region is named.",
        caption: "RevenueCat GDPR page, captured 2026-10-04: GDPR processor; no hosting region named.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "community-pro-plan-payments",
    url: "https://community.revenuecat.com/general-questions-7/questions-about-pro-plan-payments-3618",
    captured: DATE,
    full: asset("revenuecat", "community-pro-plan-payments-full-2026-10-04.png"),
    crops: [
      {
        claim: "staff-reply-1-percent-of-whole-mtr",
        file: asset("revenuecat", "community-pro-plan-payments-staff-reply-1-percent-of-whole-mtr-2026-10-04.png"),
        alt: "RevenueCat community thread: staff reply 'We won't start charging you until you hit 2500 in MTR, but pricing will still be 1% of your whole MTR, so $25.'",
        caption: "RevenueCat community thread, captured 2026-10-04: Staff reply: 1% of the whole MTR once you reach $2,500.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "github-purchases-ios-license",
    url: "https://github.com/RevenueCat/purchases-ios/blob/main/LICENSE",
    captured: DATE,
    full: asset("revenuecat", "github-purchases-ios-license-full-2026-10-04.png"),
    crops: [
      {
        claim: "mit",
        file: asset("revenuecat", "github-purchases-ios-license-mit-2026-10-04.png"),
        alt: "GitHub file view of the purchases-ios LICENSE: MIT License text.",
        caption: "RevenueCat GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-quickstart",
    url: "https://www.revenuecat.com/docs/getting-started/quickstart",
    captured: DATE,
    full: asset("revenuecat", "docs-quickstart-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-quickstart-full-1-2026-10-04.png"), asset("revenuecat", "docs-quickstart-full-2-2026-10-04.png"), asset("revenuecat", "docs-quickstart-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "platforms",
        file: asset("revenuecat", "docs-quickstart-platforms-2026-10-04.png"),
        alt: "RevenueCat SDK quickstart: install step with the platform tabs Swift, Obj-C, Kotlin, Kotlin MP, Java, Flutter, React Native, Capacitor, Cordova and Unity.",
        caption: "RevenueCat docs page, captured 2026-10-04: SDKs for every mobile platform.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-web-overview",
    url: "https://www.revenuecat.com/docs/web/overview",
    captured: DATE,
    full: asset("revenuecat", "docs-web-overview-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-web-overview-full-1-2026-10-04.png"), asset("revenuecat", "docs-web-overview-full-2-2026-10-04.png"), asset("revenuecat", "docs-web-overview-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "stripe-paddle-billing",
        file: asset("revenuecat", "docs-web-overview-stripe-paddle-billing-2026-10-04.png"),
        alt: "RevenueCat Web docs overview: RevenueCat Billing (Stripe as gateway), Stripe Billing and Paddle Billing options.",
        caption: "RevenueCat docs page, captured 2026-10-04: Web Billing with Stripe and Paddle.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-web-stripe",
    url: "https://www.revenuecat.com/docs/web/integrations/stripe",
    captured: DATE,
    full: asset("revenuecat", "docs-web-stripe-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-web-stripe-full-1-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-2-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-3-2026-10-04.png"), asset("revenuecat", "docs-web-stripe-full-4-2026-10-04.png")],
    crops: [
      {
        claim: "unlock-entitlements",
        file: asset("revenuecat", "docs-web-stripe-unlock-entitlements-2026-10-04.png"),
        alt: "RevenueCat Stripe Billing docs: sell Stripe products through hosted Web Purchase Links, the Web SDK, and unlock entitlements on mobile.",
        caption: "RevenueCat docs page, captured 2026-10-04: Stripe Billing purchases unlock entitlements in the mobile app.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-third-party-integrations",
    url: "https://www.revenuecat.com/docs/integrations/third-party-integrations",
    captured: DATE,
    full: asset("revenuecat", "docs-third-party-integrations-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-third-party-integrations-full-1-2026-10-04.png"), asset("revenuecat", "docs-third-party-integrations-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "categories",
        file: asset("revenuecat", "docs-third-party-integrations-categories-2026-10-04.png"),
        alt: "RevenueCat third-party integrations docs: categories for customer engagement, data and product analytics, with the integration list.",
        caption: "RevenueCat docs page, captured 2026-10-04: Engagement and analytics integrations.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-scheduled-data-exports",
    url: "https://www.revenuecat.com/docs/integrations/scheduled-data-exports",
    captured: DATE,
    full: asset("revenuecat", "docs-scheduled-data-exports-full-1-2026-10-04.png"),
    fullParts: [asset("revenuecat", "docs-scheduled-data-exports-full-1-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-2-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-3-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-4-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-5-2026-10-04.png"), asset("revenuecat", "docs-scheduled-data-exports-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "destinations",
        file: asset("revenuecat", "docs-scheduled-data-exports-destinations-2026-10-04.png"),
        alt: "RevenueCat scheduled data exports docs: CSV or Parquet files delivered to Amazon S3, Google Cloud Storage, Azure Blob Storage or email.",
        caption: "RevenueCat docs page, captured 2026-10-04: Scheduled exports as CSV or Parquet to S3, GCS, Azure or email.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-customer-center",
    url: "https://www.revenuecat.com/docs/tools/customer-center",
    captured: DATE,
    full: asset("revenuecat", "docs-customer-center-full-2026-10-04.png"),
    crops: [
      {
        claim: "self-service-ui",
        file: asset("revenuecat", "docs-customer-center-self-service-ui-2026-10-04.png"),
        alt: "RevenueCat Customer Center docs: a self-service UI added to the app, available on Pro and Enterprise plans.",
        caption: "RevenueCat docs page, captured 2026-10-04: A no-code Customer Center.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-llms-txt",
    url: "https://www.revenuecat.com/docs/llms.txt",
    captured: DATE,
    full: asset("revenuecat", "docs-llms-txt-full-2026-10-04.png"),
    crops: [
      {
        claim: "virtual-currency",
        file: asset("revenuecat", "docs-llms-txt-virtual-currency-2026-10-04.png"),
        alt: "RevenueCat docs index (llms.txt): the Products & Offerings section covers offerings, product configuration and virtual currency.",
        caption: "RevenueCat docs page, captured 2026-10-04: Virtual currency and offerings in the docs.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-platform-resources-llms-txt",
    url: "https://www.revenuecat.com/docs/platform-resources/llms.txt",
    captured: DATE,
    full: asset("revenuecat", "docs-platform-resources-llms-txt-full-2026-10-04.png"),
    crops: [
      {
        claim: "amazon-galaxy",
        file: asset("revenuecat", "docs-platform-resources-llms-txt-amazon-galaxy-2026-10-04.png"),
        alt: "RevenueCat platform resources index: Amazon Platform Resources and Galaxy Store setup pages.",
        caption: "RevenueCat docs page, captured 2026-10-04: Amazon Appstore and Samsung Galaxy Store support.",
      },
    ],
  },
  {
    vendor: "RevenueCat",
    page: "docs-ai-toolkit",
    url: "https://www.revenuecat.com/docs/tools/ai-toolkit",
    captured: DATE,
    full: asset("revenuecat", "docs-ai-toolkit-full-2026-10-04.png"),
    crops: [
      {
        claim: "toolkit",
        file: asset("revenuecat", "docs-ai-toolkit-toolkit-2026-10-04.png"),
        alt: "RevenueCat AI toolkit docs: plugins, skills, an MCP server and a CLI for coding agents.",
        caption: "RevenueCat docs page, captured 2026-10-04: An AI toolkit with plugins, skills, an MCP server and a CLI.",
      },
    ],
  },
  // ---- Adapty ----
  {
    vendor: "Adapty",
    page: "home",
    url: "https://adapty.io/",
    captured: DATE,
    full: asset("adapty", "home-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "home-full-1-2026-10-04.png"), asset("adapty", "home-full-2-2026-10-04.png"), asset("adapty", "home-full-3-2026-10-04.png"), asset("adapty", "home-full-4-2026-10-04.png"), asset("adapty", "home-full-5-2026-10-04.png"), asset("adapty", "home-full-6-2026-10-04.png")],
    crops: [
      {
        claim: "hero",
        file: asset("adapty", "home-hero-2026-10-04.png"),
        alt: "Adapty homepage hero: 'RevenueOS for subscription apps' with Book a demo and Start for free buttons.",
        caption: "Adapty homepage, captured 2026-10-04: Homepage hero.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "pricing",
    url: "https://adapty.io/pricing/",
    captured: DATE,
    full: asset("adapty", "pricing-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "pricing-full-1-2026-10-04.png"), asset("adapty", "pricing-full-2-2026-10-04.png"), asset("adapty", "pricing-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "free-under-5k-then-1-percent",
        file: asset("adapty", "pricing-free-under-5k-then-1-percent-2026-10-04.png"),
        alt: "Adapty pricing plan cards: Pro is free while you earn under $5K/month, then 1% of monthly revenue after you pass $5K/month; Enterprise is custom pricing.",
        caption: "Adapty pricing page, captured 2026-10-04: Free under $5K a month, then 1% of monthly revenue.",
      },
      {
        claim: "add-ons",
        file: asset("adapty", "pricing-add-ons-2026-10-04.png"),
        alt: "Adapty pricing add-ons: Refund Saver 0.2%, Ads Manager 3.5% of ad spend, Mail 20%, payout acceleration 2.5% and attribution $0.03 per install, each free up to $5K.",
        caption: "Adapty pricing page, captured 2026-10-04: Add-on fees: Refund Saver 0.2%, Ads Manager 3.5%, Mail 20%, attribution $0.03.",
      },
      {
        claim: "templates-and-ab-tests",
        file: asset("adapty", "pricing-templates-and-ab-tests-2026-10-04.png"),
        alt: "Adapty pricing feature list: 50+ templates and AI generator, A/B tests with custom traffic splits, unlimited variants and early winner predictions.",
        caption: "Adapty pricing page, captured 2026-10-04: A/B tests with unlimited variants; 50+ templates.",
      },
      {
        claim: "soc2-and-residency",
        file: asset("adapty", "pricing-soc2-and-residency-2026-10-04.png"),
        alt: "Adapty pricing Enterprise section: 24/7 support in a dedicated Slack channel, data residency in the US or EU, SOC2 certified.",
        caption: "Adapty pricing page, captured 2026-10-04: US or EU data residency on Enterprise; SOC 2.",
      },
      {
        claim: "faq-what-counts",
        file: asset("adapty", "pricing-faq-what-counts-2026-10-04.png"),
        alt: "Adapty pricing FAQ, expanded: what counts toward monthly revenue and when the 1% starts.",
        caption: "Adapty pricing page, captured 2026-10-04: Revenue is counted before store fees; the 1% starts after $5K.",
      },
      {
        claim: "faq-migration",
        file: asset("adapty", "pricing-faq-migration-2026-10-04.png"),
        alt: "Adapty pricing FAQ, expanded: how hard it is to migrate from RevenueCat, Superwall or in-house.",
        caption: "Adapty pricing page, captured 2026-10-04: What Adapty says about migrating from RevenueCat.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "security-and-compliance",
    url: "https://adapty.io/security-and-compliance/",
    captured: DATE,
    full: asset("adapty", "security-and-compliance-full-2026-10-04.png"),
    crops: [
      {
        claim: "soc2-type-ii",
        file: asset("adapty", "security-and-compliance-soc2-type-ii-2026-10-04.png"),
        alt: "Adapty security and compliance page: SOC 2 Type II attestation with the report available under NDA, and GDPR (EU and UK).",
        caption: "Adapty security and compliance page, captured 2026-10-04: SOC 2 Type II and GDPR.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "docs-migration-from-revenuecat",
    url: "https://adapty.io/docs/migration-from-revenuecat",
    captured: DATE,
    full: asset("adapty", "docs-migration-from-revenuecat-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "docs-migration-from-revenuecat-full-1-2026-10-04.png"), asset("adapty", "docs-migration-from-revenuecat-full-2-2026-10-04.png"), asset("adapty", "docs-migration-from-revenuecat-full-3-2026-10-04.png")],
    crops: [
      {
        claim: "limits",
        file: asset("adapty", "docs-migration-from-revenuecat-limits-2026-10-04.png"),
        alt: "Adapty migration guide from RevenueCat: promotional or manually granted entitlements import as profiles without transactions; refund and billing-issue history is not carried over verbatim.",
        caption: "Adapty docs page, captured 2026-10-04: Promotional entitlements and refund history do not come across.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "github-adaptysdk-ios",
    url: "https://github.com/adaptyteam/AdaptySDK-iOS",
    captured: DATE,
    full: asset("adapty", "github-adaptysdk-ios-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "github-adaptysdk-ios-full-1-2026-10-04.png"), asset("adapty", "github-adaptysdk-ios-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "mit-license",
        file: asset("adapty", "github-adaptysdk-ios-mit-license-2026-10-04.png"),
        alt: "GitHub README of AdaptySDK-iOS: 'Adapty is available under the MIT license.'",
        caption: "Adapty GitHub page, captured 2026-10-04: The iOS SDK is MIT licensed.",
      },
    ],
  },
  {
    vendor: "Adapty",
    page: "blog-new-pricing-2026",
    url: "https://adapty.io/blog/adapty-new-pricing-2026/",
    captured: DATE,
    full: asset("adapty", "blog-new-pricing-2026-full-1-2026-10-04.png"),
    fullParts: [asset("adapty", "blog-new-pricing-2026-full-1-2026-10-04.png"), asset("adapty", "blog-new-pricing-2026-full-2-2026-10-04.png")],
    crops: [
      {
        claim: "free-to-5000",
        file: asset("adapty", "blog-new-pricing-2026-free-to-5000-2026-10-04.png"),
        alt: "Adapty blog post on its 2026 pricing: free until $5,000 in monthly tracked revenue, then 1% of revenue; Pro and Enterprise plans.",
        caption: "Adapty blog post, captured 2026-10-04: Free to $5,000 a month, then 1% of revenue.",
      },
    ],
  },
];

/** Evidence for one vendor page, e.g. evidenceFor("RevenueCat", "pricing"). */
export const evidenceFor = (vendor: string, page: string): Evidence | undefined => EVIDENCE.find((e) => e.vendor === vendor && e.page === page);
