/** Anonymous app user IDs generated by the SDKs look like $RCAnonymousID:<32 hex>. */
export const ANON_PREFIX = "$RCAnonymousID:";
export const isAnonymous = (id: string) => id.startsWith(ANON_PREFIX);

/** Short random id with a prefix, e.g. ofrng1a2b3c4d5e (RevenueCat-style object ids). */
export function newId(prefix: string, len = 10): string {
  const bytes = crypto.getRandomValues(new Uint8Array(len));
  return prefix + Array.from(bytes, (b) => (b % 36).toString(36)).join("");
}
