#!/usr/bin/env bash
# Syncs RevenueDot's SDK forks with RevenueCat upstream and re-applies our patches (prd/sdk-forks/PRD.md).
#
#   scripts/forks/sync-upstream.sh purchases-js            # one fork
#   scripts/forks/sync-upstream.sh --all                   # every fork, in dependency order
#   options: --ref <upstream ref>  (default: main; a tag such as 5.92.0 also works)
#            --no-checks  --no-push  --no-pr  --workspace <dir>
#
# For each fork:
#   1. fetch upstream (branches and tags) and origin;
#   2. branch `upstream-sync` from origin/revenuedot/main-patches and merge the upstream ref into it. Conflicts are
#      resolved to upstream's side: our changes are regenerated by the rules in step 3, so nothing is lost;
#   3. re-apply the rules (scripts/forks/apply.ts) and commit; fail if the leak scan finds RevenueCat hosts;
#   4. run the fork's checks (scripts/forks/check.ts) on the result;
#   5. push `upstream-sync` and any new upstream tags to origin, and open (or update) a PR into revenuedot/main-patches.
# It never force-pushes and never touches origin/main.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLAGSHIP="$(cd "$HERE/../.." && pwd)"
WORKSPACE="$(cd "$FLAGSHIP/.." && pwd)"
ORDER=(purchases-ios purchases-android purchases-hybrid-common purchases-js react-native-purchases purchases-flutter purchases-capacitor purchases-kmp purchases-unity cordova-plugin-purchases)
PATCH_BRANCH="$(node -p "require('$HERE/config.json').patchBranch")"
SYNC_BRANCH="$(node -p "require('$HERE/config.json').syncBranch")"
ORG="$(node -p "require('$HERE/config.json').org")"
REF=main CHECKS=1 PUSH=1 PR=1 REPOS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all) REPOS=("${ORDER[@]}") ;;
    --ref) REF="$2"; shift ;;
    --no-checks) CHECKS=0 ;;
    --no-push) PUSH=0; PR=0 ;;
    --no-pr) PR=0 ;;
    --workspace) WORKSPACE="$(cd "$2" && pwd)"; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) REPOS+=("$1") ;;
  esac
  shift
done
[[ ${#REPOS[@]} -gt 0 ]] || { echo "usage: $0 <repo>... | --all" >&2; exit 2; }

tsx() { (cd "$FLAGSHIP" && pnpm -s tsx "$@"); }
failed=()

for repo in "${REPOS[@]}"; do
  dir="$WORKSPACE/$repo"
  echo; echo "=== $repo ($dir)"
  if ! git -C "$dir" diff --quiet || ! git -C "$dir" diff --cached --quiet; then echo "  uncommitted changes, skipping"; failed+=("$repo"); continue; fi

  git -C "$dir" fetch -q upstream --prune
  git -C "$dir" fetch -q upstream --tags --force 2>/dev/null || git -C "$dir" fetch -q upstream --tags || true
  git -C "$dir" fetch -q origin --prune
  upstream_ref="upstream/$REF"; git -C "$dir" rev-parse -q --verify "$upstream_ref" >/dev/null || upstream_ref="$REF"
  upstream_sha="$(git -C "$dir" rev-parse --short "$upstream_ref^{commit}")"
  base="origin/$PATCH_BRANCH"; git -C "$dir" rev-parse -q --verify "$base" >/dev/null || base="$PATCH_BRANCH"

  if git -C "$dir" merge-base --is-ancestor "$upstream_ref" "$base"; then echo "  already contains $REF ($upstream_sha)"; continue; fi

  git -C "$dir" checkout -q -B "$SYNC_BRANCH" "$base"
  if ! git -C "$dir" merge -q --no-ff --no-edit -m "Merge upstream $REF ($upstream_sha)" "$upstream_ref"; then
    # Resolve every conflict to upstream's version (or its deletion); step 3 regenerates our side.
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      if git -C "$dir" cat-file -e "$upstream_ref:$f" 2>/dev/null; then git -C "$dir" checkout -q "$upstream_ref" -- "$f"; else git -C "$dir" rm -q -f -- "$f" >/dev/null; fi
    done < <(git -C "$dir" diff --name-only --diff-filter=U)
    git -C "$dir" add -A
    git -C "$dir" commit -q --no-edit -m "Merge upstream $REF ($upstream_sha); conflicts resolved to upstream, patches re-applied next"
    echo "  merged with conflicts resolved to upstream"
  fi

  if ! tsx scripts/forks/apply.ts --repo "$repo" --workspace "$WORKSPACE" --quiet; then echo "  rules failed: update scripts/forks/rules/$repo.json"; failed+=("$repo"); continue; fi
  git -C "$dir" add -A
  if ! git -C "$dir" diff --cached --quiet; then git -C "$dir" commit -q -m "Re-apply RevenueDot fork patches after upstream $REF ($upstream_sha)"; fi

  if [[ $CHECKS == 1 ]] && ! tsx scripts/forks/check.ts --repo "$repo" --workspace "$WORKSPACE" --ref "$SYNC_BRANCH"; then
    echo "  checks failed"; failed+=("$repo")
    [[ $PUSH == 1 ]] || continue
  fi

  if [[ $PUSH == 1 ]]; then
    git -C "$dir" push -q origin "$SYNC_BRANCH:$SYNC_BRANCH"
    git -C "$dir" push -q origin --tags 2>/dev/null || echo "  (some tags were not pushed; they already exist on origin)"
    echo "  pushed origin/$SYNC_BRANCH"
  fi
  if [[ $PR == 1 ]]; then
    title="Sync upstream $REF ($upstream_sha)"
    if gh pr view "$SYNC_BRANCH" --repo "$ORG/$repo" >/dev/null 2>&1; then
      echo "  PR already open; branch updated"
    else
      gh pr create --repo "$ORG/$repo" --base "$PATCH_BRANCH" --head "$SYNC_BRANCH" --title "$title" \
        --body "Merges RevenueCat upstream \`$REF\` ($upstream_sha) and re-applies the RevenueDot fork rules from https://github.com/$ORG/revenuedot/tree/main/scripts/forks. Checks: $([[ $CHECKS == 1 ]] && echo "ran locally, see the sync log" || echo "not run")."
    fi
  fi
done

if [[ ${#failed[@]} -gt 0 ]]; then echo; echo "Failed: ${failed[*]}"; exit 1; fi
echo; echo "Done."
