// RevenueDot: open-source, self-hostable alternative to RevenueCat. Same SDK API, free.
// This file: renders the built-in paywall icons (packages/core/src/paywalls/icons.ts) to 96 × 96 white PNGs and writes them
// into apps/server/src/services/paywall-icons.generated.ts, which the server serves at /assets/icons/{name}.png.
// Run after changing an icon:  pnpm tsx scripts/paywall-icons.ts      (uses sharp from apps/site)
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PAYWALL_ICONS, paywallIconSvg } from "../packages/core/src/paywalls/icons.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const sharp = createRequire(join(ROOT, "apps/site/package.json"))("sharp") as typeof import("sharp");

const out: string[] = [];
for (const name of Object.keys(PAYWALL_ICONS)) {
  const png = await sharp(Buffer.from(paywallIconSvg(name, "#ffffff", 96)!)).png({ compressionLevel: 9 }).toBuffer();
  out.push(`  ${JSON.stringify(name)}: ${JSON.stringify(png.toString("base64"))},`);
}
writeFileSync(join(ROOT, "apps/server/src/services/paywall-icons.generated.ts"), `// Generated by scripts/paywall-icons.ts from packages/core/src/paywalls/icons.ts. Do not edit.
// The built-in paywall icons as 96 × 96 white PNGs (base64), served at /assets/icons/{name}.png.
export const ICON_PNG: Record<string, string> = {
${out.join("\n")}
};
`);
console.log(`Wrote ${out.length} icons.`);
