/**
 * The Customer Center's predefined strings: every key the SDKs read from `localization.localized_strings`, with the
 * English text each SDK shows when the key is missing. Keys and texts come from the MIT-licensed SDK sources:
 * purchases-ios `Sources/CustomerCenter/CustomerCenterConfigData.swift` (`CommonLocalizedString.defaultValue`) plus the
 * keys only purchases-android reads (`CustomerCenterConfigData.Localization.CommonLocalizedString`).
 */
export const CC_STRINGS: Record<string, string> = {
  buy_subscription: "Subscribe",
  copy: "Copy",
  no_thanks: "No, thanks",
  no_subscriptions_found: "No Subscriptions found",
  try_check_restore: "We can try checking your Apple account for any previous purchases",
  restore_purchases: "Restore purchases",
  going_to_check_purchases: "Let’s take a look! We’re going to check your account for missing purchases.",
  check_past_purchases: "Check past purchases",
  purchases_recovered: "Purchases restored",
  purchases_restoring: "Restoring...",
  purchases_recovered_explanation: "We restored your past purchases and applied them to your account.",
  purchases_not_found: "No past purchases",
  purchases_not_recovered: "We could not find any purchases with your account. If you think this is an error, please contact support.",
  cancel: "Cancel",
  resubscribe: "Resubscribe",
  billing_cycle: "Billing cycle",
  current_price: "Price",
  expired: "Expired",
  expires: "Expires",
  next_billing_date: "Next billing date",
  refund_canceled: "Refund canceled",
  refund_error_generic: "An error occurred while processing the refund request. Please try again.",
  refund_granted: "Refund requested",
  refund_status: "Refund status",
  sub_earliest_expiration: "This is your subscription with the earliest expiration date.",
  sub_earliest_renewal: "This is your subscription with the earliest billing date.",
  sub_expired: "This subscription has expired.",
  contact_support: "Contact support",
  default_body: "Please describe your issue or question.",
  default_subject: "Support Request",
  dismiss: "Dismiss",
  done: "Done",
  unknown: "Unknown",
  update_warning_title: "Update available",
  update_warning_description: "Downloading the latest version of the app may help solve the problem.",
  update_warning_update: "Update",
  update_warning_ignore: "Continue",
  platform_mismatch: "Platform mismatch",
  please_contact_support: "Please contact support to manage your subscription.",
  apple_subscription_manage: "You have an active subscription from the Apple App Store. You can manage your subscription by using the App Store app on an Apple device.",
  google_subscription_manage: "You have an active subscription from the Google Play Store",
  amazon_subscription_manage: "You have an active subscription from the Amazon Appstore. You can manage your subscription in the Amazon Appstore app.",
  web_subscription_manage: "You have an active subscription that was purchased on the web. You can manage your subscription using the button below.",
  manage_subscription: "Manage your subscription",
  you_have_promo: "You’ve been granted a subscription that doesn’t renew",
  you_have_lifetime: "Your active lifetime subscription",
  free: "Free",
  never: "Never",
  screen_management_see_all_purchases: "See All Purchases",
  purchase_info_purchased_on_date: "Purchased on {{ date }}",
  purchase_info_expired_on_date: "Expired on {{ date }}",
  purchase_info_renews_on_date: "Renews on {{ date }}",
  purchase_info_expires_on_date: "Expires on {{ date }}",
  screen_purchase_history_active_subscriptions_title: "Active Subscriptions",
  screen_purchase_history_expired_subscriptions_title: "Expired Subscriptions",
  screen_purchase_history_others_title: "Other",
  screen_purchase_history_account_details_title: "Account Details",
  screen_purchase_history_original_purchase_date: "Original Download Date",
  screen_purchase_history_user_id: "User ID",
  screen_purchase_history_title: "Purchase History",
  shared_through_family_member: "Shared through family member",
  active: "Active",
  inactive: "Inactive",
  introductory_price: "Introductory Price",
  trial_period: "Trial Period",
  product_name: "Product Name",
  paid_price: "Paid Price",
  original_download_date: "Original Download Date",
  history_latest_purchase_date: "Latest Purchase Date",
  status: "Status",
  next_renewal: "Next Renewal",
  unsubscribed_at: "Unsubscribed At",
  billing_issue_detected_at: "Billing Issue Detected At",
  grace_period_expires_at: "Grace Period Expires At",
  period_type: "Period Type",
  refunded_at: "Refunded At",
  store: "Store",
  product_id: "Product ID",
  sandbox: "Sandbox",
  transaction_id: "Transaction ID",
  yes: "Yes",
  no: "No",
  app_store: "Apple App Store",
  mac_app_store: "Mac App Store",
  google_play_store: "Google Play Store",
  stripe: "Stripe",
  promotional: "Promotional",
  amazon_store: "Amazon Store",
  card_store_promotional: "Via Support",
  external_store: "External Purchases",
  unknown_store: "Unknown Store",
  store_paddle: "Paddle",
  store_web: "Web",
  type_subscription: "Subscription",
  type_one_time_purchase: "One-time Purchase",
  virtual_currency_balances_screen_header: "In-App Currencies",
  see_all_virtual_currencies: "See all in-app currencies",
  no_virtual_currency_balances_found: "It doesn't look like you've purchased any in-app currencies.",
  you_may_have_duplicated_subscriptions_title: "You may have duplicated subscriptions",
  you_may_have_duplicated_subscriptions_subtitle: "You might be subscribed both on the web and through the App Store.To avoid being charged twice, please cancel your iOS subscription in your device settings.",
  price_paid: "Paid {{ price }}.",
  expires_on_date_without_changes: "Expires on {{ date }} without further charges.",
  renews_on_date_for_price: "Renews on {{ date }} for {{ price }}.",
  renews_on_date: "Renews on {{ date }}.",
  renews_on_date_with_last_paid_price: "Renews on {{ date }}. Last paid {{ price }}.",
  price_afterwards: "{{ price }} afterwards.",
  free_trial_until_date: "Free trial until {{ date }}.",
  price_expires_on_date_without_changes: "{{ price }}. Expires on {{ date }} without changes.",
  badge_lifetime: "Lifetime",
  badge_cancelled: "Cancelled",
  badge_free_trial: "Free trial",
  badge_free_trial_cancelled: "Cancelled trial",
  refund_success: "Apple has received the refund request",
  actions_section_title: "Actions",
  subscriptions_section_title: "Subscriptions",
  purchases_section_title: "Purchases",
  test_store: "Test Store",
  galaxy_store: "Galaxy Store",
  support_ticket_create: "Create a support ticket",
  email: "Email",
  enter_email: "Enter your email",
  description: "Description",
  sent: "Message sent",
  support_ticket_failed: "Failed to send, please try again.",
  submit_ticket: "Submit ticket",
  character_count: "{{ count }} characters",
  ios_promo_offer_button_regular_price: "then {{ price }}",
  ios_promo_offer_button_free_trial: "{{ duration }} for free",
  ios_promo_offer_button_recurring_discount: "{{ price }} during {{ duration }}",
  ios_promo_offer_button_upfront_payment: "{{ duration }} for {{ price }}",
  free_trial_then_price: "First {{ sub_offer_duration }} free, then {{ price }}",
  single_payment_then_price: "{{ sub_offer_duration }} for {{ sub_offer_price }}, then {{ price }}",
  discounted_recurring_then_price: "{{ sub_offer_price }} during {{ sub_offer_duration }}, then {{ price }}",
  free_trial_single_payment_then_price: "Try {{ sub_offer_duration }} for free, then {{ sub_offer_duration_2 }} for {{ sub_offer_price_2 }}, and {{ price }} thereafter",
  web_store: "Web",
  last_charge_was: "Last charge: {{ price }}",
  next_billing_date_on: "Next billing date: {{ date }}",
  invalid_email_error: "Please enter a valid email address",
  characters_remaining: "{{ count }} characters",
  free_trial_discounted_then_price: "Try {{ sub_offer_duration }} for free, then {{ sub_offer_price_2 }} during {{ sub_offer_duration_2 }}, and {{ price }} thereafter",
  discounted_recurring_payment_then_price: "{{ discounted_recurring_payment_price_per_period }} for {{ discounted_recurring_payment_cycles }} periods, then {{ price }}",
  free_trial_discounted_recurring_payment_then_price: "Try {{ sub_offer_duration }} for free, then {{ discounted_recurring_payment_price_per_period }} for {{ discounted_recurring_payment_cycles }} periods, and {{ price }} thereafter",
};
